# extend.conf
PG_DEB_DIR="/var/lib/docker-pgagent/apt/pkg"
PG_RUN_AGENT="/usr/bin/pgagent host=/var/run/postgresql dbname=postgres user=postgres -s /var/log/postgresql/pgagent.log"
PG_SYS_EXTEND="tree pgagent curl postgresql-plpython3-17 python3-requests python3-pip net-tools procps"
PG_UPD_STATUS="/var/lib/docker-pgagent-prep.state"